In [1]:
import numpy as np
import pandas as pd

In [2]:
data = np.load('PEMS04.npz')

In [26]:
flow_data = data['data'].transpose([1, 0, 2])
flow_data.shape

(307, 16992, 3)

In [9]:
flow_data = flow_data[:,:,0]
flow_data

array([[62., 61., 71., ..., 66., 77., 74.],
       [56., 40., 28., ..., 76., 73., 71.],
       [90., 94., 79., ..., 77., 96., 64.],
       ...,
       [56., 51., 67., ..., 85., 69., 80.],
       [48., 30., 31., ..., 58., 52., 78.],
       [38., 35., 45., ..., 57., 43., 40.]])

In [11]:
flow_data[0].shape

(16992,)

In [12]:
flow_data = flow_data[:, :, np.newaxis]
flow_data

array([[[62.],
        [61.],
        [71.],
        ...,
        [66.],
        [77.],
        [74.]],

       [[56.],
        [40.],
        [28.],
        ...,
        [76.],
        [73.],
        [71.]],

       [[90.],
        [94.],
        [79.],
        ...,
        [77.],
        [96.],
        [64.]],

       ...,

       [[56.],
        [51.],
        [67.],
        ...,
        [85.],
        [69.],
        [80.]],

       [[48.],
        [30.],
        [31.],
        ...,
        [58.],
        [52.],
        [78.]],

       [[38.],
        [35.],
        [45.],
        ...,
        [57.],
        [43.],
        [40.]]])

In [13]:
flow_data.shape

(307, 16992, 1)

In [37]:
date_data = flow_data[:,0,:]
date_data[0]

array([6.20e+01, 7.70e-03, 6.79e+01])